### PR TITLE
WIP: Async build leaderboards

### PR DESCRIPTION
**Pull request by bugant**
See https://github.com/potomak/tomatoes/issues/206.

### CODE REVIEW

**Comment by dalpo** [comment]
@bugant Great job!

About the leaderboards I was thinking that would be interesting to create a new `UserRanking` model containing all leaderboard data instead of using the existing implementations with the data splitted into many collections.

I'm not sure what is the best way to manage a timeseries with mongodb but I'm thinking that we could create a document record per day containing all day user's tomatoes instead per `user * time_period` reducing the size of the collection.

For instance a sample document/record would be like this:
```
{
  timestamp: ISODate("2016-11-02T00:00:00.000Z"),
  tomatoes: {
    1: 14,
    17: 3,
    ...
  }
}
```

Where the tomatoes object keys are the user ids and their values are the amount of tomatoes per user.

Currently I'm figuring out how to easily query and aggregate this kind of data without the use of map/reduce. 

Let me know what you and @potomak think about this idea.

**Comment by potomak** [comment]
> Currently I'm figuring out how to easily query and aggregate this kind of data without the use of map/reduce.

This should be straightforward, that's the main reason we're doing this. The idea is that for each `UserRanking*` collection there would be only as many documents as the users in that leaderboard, and a simple index on the `value` attribute would do the trick.

```ruby
@leaderboard_users = UserRandingToday.order_by([[:value, :desc], [:_id, :desc]]).page params[:page]```

> Where the `tomatoes` object keys are the user ids and their values are the amount of tomatoes per user.

This would increase concurrent access on documents, I'm not sure I want to do this.

I like the idea of storing documents in one collection only. We could store documents like:

```
{
  'user_id': ...,
  'date': '2016-11-02',
  'value': 12
}
```

If we add an index on `date` then we could sum all the `values` by `user_id` to present weekly and monthly leaderboards.

**Comment by bugant** [comment]
@dalpo @potomak the goal here is to avoid map/reduce operations, so I think the best thing is to keep a model for each leaderboard type: this way you will just order by score and you have your leaderboard ready. I was also thinking that Redis would be a perfect fit to store leaderboards but I'm not sure if you would like to add it as a dependency: it could help if we want to show a user's rank and information like that.

Anyway, I would like to do a bit of research on what's the best way to store leaderboards on MongoDB and see what is the most used/recommended approach.

**Comment by potomak** [comment]
I found this post online that is worth a read: http://openmymind.net/2011/5/8/Practical-NoSQL-Solving-a-Real-Problem-w-Mongo-Red/ by @karlseguin

The problem is similar and the solution proposed is also similar, with the only exception that the author wanted to support user ranks as well and he used Redis' zset to do it.

One thing we're doing wrong is naming. `value` is too generic, let's use `count` or `score`. Let's avoid using the word "rank" for things that are not ranks.

**Comment by potomak** [comment]
Superseded by https://github.com/potomak/tomatoes/pull/210.

**Pull request closed without merging**
