### PR TITLE
Add .env file to store development ENV variables

### PR DESCRIPTION
**Pull request by dalpo**

### CODE REVIEW

**Comment by potomak** [comment]
@dalpo is `SESSION_STORE_SECRET_TOKEN` the only env variable needed in dev?

**Comment by dalpo** [comment]
@potomak yes, actually :)

**Comment by bugant** [comment]
@dalpo I think it would be good to move all config to the `.env` file

**Comment by potomak** [comment]
@dalpo I agree with @bugant

**Comment by potomak** [comment]
I incurred on the same issue and I think that an easiest fix would be to add a default `SESSION_STORE_SECRET_TOKEN` if the env variable is not present. I will open a PR to do it.

**Pull request closed without merging**
