### PR TITLE
Update Ruby version

### PR DESCRIPTION
**Pull request by potomak**
Depends on https://github.com/potomak/tomatoes/pull/160.

### CODE REVIEW

**Comment by dalpo** [comment]
@potomak Does rails 3.2.22.4 work with ruby 2.3.1?

https://github.com/rails/rails/issues/26229

**Comment by potomak** [comment]
@dalpo interesting... From what I saw it was working fine, but I already opened a PR to update Rails as well, see https://github.com/potomak/tomatoes/pull/160.

**Comment by dalpo** [comment]
@potomak Ok, we could try to update to rails 4.x before merging this.

**Comment by potomak** [comment]
@dalpo ok, I'll add a note in the description.

**Pull request merged**
